taskcluster/get_task.go
The taskcluster proxy retrieves a task definition from the queue in order to read the scopes. Formerly, it was reading a bunch of fields that were unused. This broke when "priority" was re-added (presumably it existed a while ago) but now as a string (it was formerly an int, by the look of things).
Therefore we should only read "scopes" since that is all that is processed, and task definition can evolve over time, so no reason to read stuff that could break if the task definition changes.
=> Bug 1187331 - remove unused/incorrect fields from task definition.

main.go
Note, the --version option existed natively in docopt, it just wasn't included in the help text.
=> Bug 1234890 - update help text to show --version option

routes.go
This extra information can only be useful.
=> Bug 1234890 - add a response header with taskcluster proxy version

routes.go
Generally I think the proxy have taken a bad direction...
This will support services that only do JSON like the ones we have...
But really, we should support signing any request on the form: `taskcluster/<host>/<path>`
Hence, queue would be `taskcluster/queue.taskcluster.net/v1/ping`
This way, anyone who adds taskcluster authentication to his app, can use the proxy...
But to this we need to not use TC-client for this... because we want to be streaming the result through not storing it in memory... This is important as some services may take huge payloads. I dream that maybe one day releng-api, balrog, who knows could use TC creds...
For them it's pretty simple to call `auth.tc.net` with the `authorization` header and ask if the request has a certain scope. So it's not completely …
=> Fix broken proxy... dummy body and missing response

README.md, authorization_test.go, routes.go
Unfortunately it seems I broke things. This PR has a fix and also adds a couple of tests:
1. Making sure that proxy requests with http request bodies (a.k.a payloads) work
2. Making sure that even when a request is not successful (e.g. http 400 from endpoint) that the message body is also proxied back to the requester, and not only in success cases.
=> Bug 1241107 - fix taskcluster-proxy to work with http request payloads

taskcluster/services.go
Later we should generate urls dynamically - but for now just adding github service which has now been moved to github.taskcluster.net.
=> Added github service to taskcluster-proxy

authorization_test.go, routes.go, test.js
This adds the following headers to taskcluster-proxy http responses:
* `X-Taskcluster-Proxy-Temp-Scopes` (the unexpanded scopes the proxy has been granted, if using temporary credentials)
* `X-Taskcluster-Authorized-Scopes` (the unexpanded scopes the proxy has granted to the task)
This is to make it easier to audit which scopes the proxy has in general, and which scopes it has granted to the task, without relying on detailed information in error responses from the auth service.
Please note if the proxy is running with permanent credentials, it will not inject the `X-Taskcluster-Proxy-Temp-Scopes` header.
=> Bug 1234929 - add extra headers for troubleshooting scopes issues

README.md, authorization_test.go, credentials_update_test.go, main.go, routes.go
docker-worker will use task temporary credentials for taskcluster
requests on task behalf.
During task reclaim, the temporary credentials might be updated, and
if using taskcluster-proxy to forward requests, we should update the
credentials in the proxy as well.
We create a "/Credentials" endpoint which receive PUT requests with
a json body containing the new credentials data for update.
=> Bug 1220738: Create endpoint for credentials update. r=pmoore

authorization_test.go
Some requests in Taskcluster were updated to return status codes that
better reflect the error occurred. We update the expected http codes
to reflect these new returned status.
=> Fix http test status codes.

authorization_test.go, credentials_update_test.go, routes.go
I split out the json handling in `APICall` so there is now a client method `Request` that takes binary input and returns binary output, and `APICall` uses this, so no change to `APICall` functionality. However, taskcluster-proxy can now call the Request method directly, so doesn't need to pass json in/out but can proxy arbitrary binary data.
See associated change https://github.com/taskcluster/taskcluster-client-go/commit/f23fbec12ab177b9cf8d9e4a4e00fe0a1873e26c which made this possible.
=> Handle non-json responses from API calls

authorization_test.go, credentials_update_test.go, main.go, routes.go
Also this adds the X-Taskcluster-Proxy http response headers to the /credentials endpoint...
This also fixes the bug where if the url path was shorter than 5 characters, there would be no response because the request would cause a panic.
=> Use http handlers for different endpoints

authorization_test.go, routes.go
This becomes useful now that we have named temp credentials.
Originated from review comment https://github.com/taskcluster/taskcluster-proxy/pull/18#discussion_r53009944 (which I only spotted after merging the PR - d'oh).
=> Capture temp creds clientId in http response headers too

.travis.yml, authorization_test.go, credentials_update_test.go, main.go, routes.go
Upstream removed `CallSummary` and made some lint fixes.
=> Adapted to work with upstream changes in taskcluster-client-go

authorization_test.go, credentials_update_test.go, main.go, routes.go
This depends on taskcluster/taskcluster-client-go#15 so I would expect travis to fail for this PR until that has landed. When the other PR lands, you should be able to rerun the travis jobs on this PR.
=> Bug 1285197 - fix go get warning for taskcluster-client-go

README.md, build.sh, main.go
```
pmoore@Petes-iMac:~/go/src/github.com/taskcluster/taskcluster-proxy bug1394894 $ taskcluster-proxy --task-id -XxUtCX2SR2DA9Y7sOQ49g
2017/08/30 12:06:06 clientId: 'mozilla-ldap/pmoore@mozilla.com/dev'
2017/08/30 12:06:06 accessToken: '***************'
2017/08/30 12:06:06 Warning - no taskcluster certificate set - assuming permanent credentials are being used
2017/08/30 12:06:06 taskId: '-XxUtCX2SR2DA9Y7sOQ49g'
2017/08/30 12:06:08 Proxy with scopes:  [queue:define-task:aws-provisioner-v1/gecko-3-b-linux queue:create-task:aws-provisioner-v1/gecko-3-b-linux queue:define-task:aws-provisioner-v1/build-c4-2xlarge queue:create-task:aws-provisioner-v1/build-c4-2xlarge secrets:get:project/releng/snapcraft/firefox/edge]
...
...
```
Note, I _intentionally_ made supplying of a `taskId` optional, …
=> Bug 1394894 - support taskIds starting with a '-'

authorization_test.go
This new test fails when the taskcluster-client-go fix from bug 1405889 is not applied with:
```
--- FAIL: TestRetrievePrivateArtifact (1.48s)
authorization_test.go:148: Expected status code 200 but got 403
authorization_test.go:149: Headers: map[X-Taskcluster-Proxy-Perm-Clientid:[mozilla-ldap/pmoore@mozilla.com/dev] X-Taskcluster-Endpoint:[https://queue.taskcluster.net/v1/task/KTBKfEgxR5GdfIIREQIvFQ/runs/0/artifacts/SampleArtifacts%2F_%2FX.txt] X-Amz-Request-Id:[***********] X-Amz-Id-2:[*************] Content-Type:[application/xml] Date:[Thu, 05 Oct 2017 17:39:32 GMT] Server:[AmazonS3] X-Taskcluster-Proxy-Version:[Taskcluster proxy 4.0.1]]
authorization_test.go:150: Response received:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request …
```
=> Bug 1405889 - Add unit test for retrieval of a private artifact

.travis.yml, routes.go
Two changes here:
1) Use go 1.9 in travis (and travis config cleanup)
2) Use read lock when reading credentials (see #26)
=> Read lock credentials and use go 1.9

README.md, credentials_update_test.go, main.go, parse_test.go, testdata/tasks/KTBKfEgxR5GdfIIREQIvFQ.json, testdata/tasks/README.md, testdata/tasks/eQgo-rE5RHWgHeYRKGrHKA.json
There was a bug in the command line parsing of `taskcluster-proxy`. You can specify a command line option for a task ID, which should cause taskcluster-proxy to restrict the scopes of outbound requests to those of the supplied task ID. However, if a task ID was specified that happened to have no scopes itself, the full scopes of the taskcluster-proxy client ID would be attached to outbound requests.
The correct behaviour should be, if the task has no scopes, `AuthorizedScopes` should be set to an empty string array (rather than a nil string array). The subtle difference is that a nil `AuthorizedScopes` means, "don't restrict this client to a set of authorized scopes", whereas an empty string array for `AuthorizedScopes` means "restrict this client to have precisely no scopes".
I've pulled …
=> Ensure AuthorizedScopes is non-nil if --task-id is specified

.travis.yml
This should prevent the default install command:
```
go get -v -t ./...
```
running before our custom install command:
```
CGO_ENABLED=0 go get -v -t -ldflags "-X main.revision=$(git rev-parse HEAD)" ./...
```
This should fix the issue of the git revision not being set in the binary release of taskcluster-proxy.
See [bug comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1452095#c33) for details.
=> Overwrite install step in travis

.travis.yml, release.sh
I spotted that the CI broke due to upstream issue travis-ci/gimme#154 so disabling arm64 builds until this is resolved, or we may choose not to use gimme in favour of a native go binary installation (since go natively supports cross compilation, so gimme isn't really needed).
=> Fix CI bustage and release script

build.sh
We are not sure why this was here - perhaps a copy-paste error?  But it
deletes local files that I would like it not to delete!
=> remove 'git clean' command from build process
